baseURL: "http://localhost:1313/"
title: "emmanuel io"
theme: PaperMod

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

enableRobotsTXT: true
googleAnalytics: ''
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

languages:
  en:
    contentDir: content
    # disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    # weight: 1
    params:
      profileMode:
        enabled: true
        title: |
          emmanuel io  
          Digital Solutions Developer
        subtitle: |
          I design fast, maintainable software that delivers lasting value.  
          100&nbsp;% remote, performance-driven
        imageUrl: "images/emmanuel-io-avatar-400x400.png"
        imageTitle: "My photo"
        imageWidth: 400
        imageHeight: 400
        buttons:
          - name: "Read blog"
            url: "/posts/"
          - name: "About"
            url: "/about/"
  fr:
    contentDir: content
    # disabled: false
    languageCode: fr-FR
    languageDirection: ltr
    languageName: Français
    # weight: 2
    params:
      profileMode:
        enabled: true
        title: |
          emmanuel io  
          Développeur de solutions numériques
        subtitle: |
          Je conçois des logiciels rapides et durables, pensés pour créer de la valeur.  
          100&nbsp;% à distance, axé performance
        imageUrl: "images/emmanuel-io-avatar-400x400.png"
        imageTitle: "Ma photo"
        imageWidth: 400
        imageHeight: 400
        buttons:
          - name: "Blog"
            url: "/fr/posts/"
          - name: "À propos"
            url: "/fr/about/"

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

minify:
  disableXML: true
  minifyOutput: true

privacy:
  vimeo:
    disabled: false
    simple: true
  x:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true

# Enable Open Graph & Twitter
enableOpenGraph: true
enableTwitterCards: true