en:
  contentDir: content
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: English
  weight: 1
fr:
  contentDir: content
  disabled: false
  languageCode: fr-FR
  languageDirection: ltr
  languageName: Français
  weight: 2
