main:
- identifier: archive
  name: Archive
  title: Archive
  url: /posts/
  weight: 0
- name: About
  url: about/
  weight: 1
- name: Posts
  url: posts/
  weight: 2
- name: Categories
  url: categories/
  weight: 3
- identifier: tags
  name: tags
  url: /tags/
  weight: 4
- name: Search
  url: search/
  weight: 5
