main:
  - name: À propos
    url: /fr/about/
    weight: 1
  - name: Articles
    url: /fr/posts/
    weight: 2
  - name: Catégories
    url: /fr/categories/
    weight: 3
  - identifier: tags
    name: Tags
    url: /fr/tags/
    weight: 4
  - name: Recherche
    url: /fr/search/
    weight: 5
  - name: CV
    url: /cv/
    weight: 6