profileMode:
  enabled: true
  title: Emmanuel IO
  subtitle: Développeur backend · FastAPI · Hugo
  imageUrl: images/emmanuel-io-avatar.png
  buttons:
  - name: Articles
    url: posts
  - name: À propos
    url: about
  - name: GitHub
    url: https://github.com/emmanuel-io
