author: Emmanuel IO
authorAvatar: images/emmanuel-io-avatar.png
ShowReadingTime: true
ShowCodeCopyButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowLangSwitch: true
ShowFullTextinRSS: true
ShowToc: true
TocOpen: false
ShowPageNums: true
profileMode:
  enabled: true
  title: Emmanuel IO
  subtitle: Backend Dev · FastAPI Fan · Hugo Builder
  imageUrl: images/emmanuel-io-avatar.png
  imageTitle: Emmanuel's avatar
  imageWidth: 120
  imageHeight: 120
  buttons:
  - name: Posts
    url: posts
  - name: About
    url: about
  - name: GitHub
    url: https://github.com/emmanuel-io
