author: emmanuel io
authorAvatar: images/emmanuel-io-avatar-400x400.png

ShowPostList: true
ShowReadingTime: true
ShowCodeCopyButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowLangSwitch: true
ShowFullTextinRSS: true
ShowShareButtons: true
ShowToc: true
TocOpen: false
ShowPageNums: true

sortByDate: desc

defaultTheme: dark

socialIcons:
  - name: github
    url: "https://github.com/emmanuel-io"
  - name: linkedin
    url: "https://www.linkedin.com/in/emmanuelamadio/"
  - name: email
    url: "mailto:emmanuel.amadio@gmail.com"
  - name: x
    url: "https://x.com/emmanuel_i_o"


# assets:
#   css:
#     - css/extra.css

# maxImageWidth: 1234
# maxImageWidth:
#   en: 1200
#   fr: 1600